run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/bohdanch-w/rand-api
  cyclop:
    max-complexity: 30
  wrapcheck:
    ignoreSigs:
      - web.Respond
      - web.NewError
      - fmt.Errorf
  nolintlint:
    allow-leading-space: true
  dupl:
    threshold: 400

linters:
  enable-all: true
  disable:
  # deprecated:
    - ifshort
    - varcheck
    - deadcode
    - golint
    - structcheck
    - interfacer
    - nosnakecase
    - maligned
    - scopelint
    - exhaustivestruct
    
  # generics:
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    - gci
    - varnamelen
    - predeclared
    - paralleltest
    - exhaustruct
    - gofmt
    - gofumpt
    - goimports
    - nolintlint