run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/bohdanch-w/rand-api
  cyclop:
    max-complexity: 30
  wrapcheck:
    ignoreSigs:
      - web.Respond
      - web.NewError
      - fmt.Errorf

linters:
  enable-all: true
  disable:
    - gci
    - exhaustivestruct
    - varnamelen
    - predeclared
    - paralleltest
    - exhaustruct
